from http.server import BaseHTTPRequestHandler, HTTPServer
import json

class Handler(BaseHTTPRequestHandler):
    def do_POST(self):
        length = int(self.headers.get('content-length', 0))
        _ = self.rfile.read(length)
        body = {"text": json.dumps({"title": "Mock Engineer", "company": "ExampleCorp", "location": "Remote", "description": "Generated by mock"})}
        self.send_response(200)
        self.send_header('Content-Type', 'application/json')
        self.end_headers()
        self.wfile.write(json.dumps(body).encode())

    def log_message(self, format, *args):
        return

if __name__ == '__main__':
    server = HTTPServer(('0.0.0.0', 18081), Handler)
    server.serve_forever()
